//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryTable
    {
        public string UserId { get; set; }
        public string CollegesId { get; set; }
        public string JobsName { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public Nullable<double> TrialScore { get; set; }
    
        public virtual Jobs Job { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
